jogadores = [
    {
        "id": 1,
        "nome": "Adriano Imperador",
        "rkng2000": 6,
        "rkngContemp": 19,
        "rkng90-": 15,
        "epoca": 2,
    },
    {
        "id": 2,
        "nome": "Aguero",
        "rkng2000": 30,
        "rkngContemp": 13,
        "rkng90-": 30,
        "epoca": 3,
    },
    {
        "id": 3,
        "nome": "Batistuta",
        "rkng2000": 15,
        "rkngContemp": 28,
        "rkng90-": 8,
        "epoca": 1,
    },
    {
        "id": 4,
        "nome": "Benzema",
        "rkng2000": 23,
        "rkngContemp": 4,
        "rkng90-": 23,
        "epoca": 3,
    },
    {
        "id": 5,
        "nome": "Bergkamp",
        "rkng2000": 20,
        "rkngContemp": 30,
        "rkng90-": 10,
        "epoca": 1,
    },
    {
        "id": 6,
        "nome": "Cristiano Ronaldo",
        "rkng2000": 9,
        "rkngContemp": 2,
        "rkng90-": 16,
        "epoca": 2,
    },
    {
        "id": 7,
        "nome": "Del Piero",
        "rkng2000": 7,
        "rkngContemp": 20,
        "rkng90-": 14,
        "epoca": 2,
    },
    {
        "id": 8,
        "nome": "Drogba",
        "rkng2000": 5,
        "rkngContemp": 18,
        "rkng90-": 19,
        "epoca": 2,
    },
    {
        "id": 9,
        "nome": "Eto'o",
        "rkng2000": 4,
        "rkngContemp": 16,
        "rkng90-": 17,
        "epoca": 2,
    },
    {
        "id": 10,
        "nome": "Gabigol",
        "rkng2000": 24,
        "rkngContemp": 7,
        "rkng90-": 28,
        "epoca": 3,
    },
    {
        "id": 11,
        "nome": "Garrincha",
        "rkng2000": 16,
        "rkngContemp": 27,
        "rkng90-": 4,
        "epoca": 1,
    },
    {
        "id": 12,
        "nome": "Gerd Muller",
        "rkng2000": 17,
        "rkngContemp": 29,
        "rkng90-": 6,
        "epoca": 1,
    },
    {
        "id": 13,
        "nome": "Haaland",
        "rkng2000": 26,
        "rkngContemp": 6,
        "rkng90-": 26,
        "epoca": 3,
    },
    {
        "id": 14,
        "nome": "Harry Kane",
        "rkng2000": 27,
        "rkngContemp": 9,
        "rkng90-": 25,
        "epoca": 3,
    },
    {
        "id": 15,
        "nome": "Ibrahimovic",
        "rkng2000": 10,
        "rkngContemp": 12,
        "rkng90-": 20,
        "epoca": 2,
    },
    {
        "id": 16,
        "nome": "Johan Cruijff",
        "rkng2000": 18,
        "rkngContemp": 25,
        "rkng90-": 5,
        "epoca": 1,
    },
    {
        "id": 17,
        "nome": "Lewandowski",
        "rkng2000": 25,
        "rkngContemp": 8,
        "rkng90-": 21,
        "epoca": 3,
    },
    {
        "id": 18,
        "nome": "Luis Suárez",
        "rkng2000": 28,
        "rkngContemp": 10,
        "rkng90-": 27,
        "epoca": 3,
    },
    {
        "id": 19,
        "nome": "Lukaku",
        "rkng2000": 29,
        "rkngContemp": 11,
        "rkng90-": 29,
        "epoca": 3,
    },
    {
        "id": 20,
        "nome": "Maradona",
        "rkng2000": 14,
        "rkngContemp": 22,
        "rkng90-": 3,
        "epoca": 1,
    },
    {
        "id": 21,
        "nome": "Mbappé",
        "rkng2000": 21,
        "rkngContemp": 3,
        "rkng90-": 22,
        "epoca": 3,
    },
    {
        "id": 22,
        "nome": "Messi",
        "rkng2000": 8,
        "rkngContemp": 1,
        "rkng90-": 18,
        "epoca": 2,
    },
    {
        "id": 23,
        "nome": "Neymar Jr",
        "rkng2000": 22,
        "rkngContemp": 5,
        "rkng90-": 24,
        "epoca": 3,
    },
    {
        "id": 24,
        "nome": "Pelé",
        "rkng2000": 11,
        "rkngContemp": 23,
        "rkng90-": 1,
        "epoca": 1,
    },
    {
        "id": 25,
        "nome": "Romário",
        "rkng2000": 13,
        "rkngContemp": 24,
        "rkng90-": 2,
        "epoca": 1,
    },
    {
        "id": 26,
        "nome": "Ronaldo Fenômeno",
        "rkng2000": 12,
        "rkngContemp": 17,
        "rkng90-": 7,
        "epoca": 1,
    },
    {
        "id": 27,
        "nome": "Rooney",
        "rkng2000": 3,
        "rkngContemp": 14,
        "rkng90-": 13,
        "epoca": 2,
    },
    {
        "id": 28,
        "nome": "Shevchenko",
        "rkng2000": 2,
        "rkngContemp": 21,
        "rkng90-": 12,
        "epoca": 2,
    },
    {
        "id": 29,
        "nome": "Thierry Henry",
        "rkng2000": 1,
        "rkngContemp": 15,
        "rkng90-": 11,
        "epoca": 2,
    },
    {
        "id": 30,
        "nome": "Van Basten",
        "rkng2000": 19,
        "rkngContemp": 26,
        "rkng90-": 9,
        "epoca": 1,
    },
]
